all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.92, mac: '6c:4b:90:2a:6a:97', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.1.82, mac: '6c:4b:90:2e:8d:82', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.1.66, mac: '6c:4b:90:2b:95:5d', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.1.85, mac: '6c:4b:90:47:96:35', disk: sda, network_interface: eno1}
        metal4: {ansible_host: 192.168.1.91, mac: '6c:4b:90:47:90:17', disk: sda, network_interface: eno1}
        metal5: {ansible_host: 192.168.1.68, mac: '6c:4b:90:47:8e:fa', disk: sda, network_interface: eno1}
        metal6: {ansible_host: 192.168.1.97, mac: '6c:4b:90:47:92:07', disk: sda, network_interface: eno1}
