all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
    - 192.168.1.220/27
metal:
  children:
    masters:
      hosts:
        control-plane-metal0: {ansible_host: 192.168.1.128, mac: '6c:4b:90:80:ce:22', disk: sda, network_interface: eth0}
        control-plane-metal1: {ansible_host: 192.168.1.99, mac: '6c:4b:90:2e:8d:82', disk: sda, network_interface: eth0}
        control-plane-metal2: {ansible_host: 192.168.1.44, mac: '00:23:24:e7:21:e1', disk: sda, network_interface: eth0}
    workers:
      hosts:
        worker-metal1: {ansible_host: 192.168.1.250, mac: '6c:4b:90:62:22:0a', disk: sda, network_interface: eth0}
        worker-metal2: {ansible_host: 192.168.1.249, mac: '6c:4b:90:0c:7f:66', disk: sda, network_interface: eth0}
        worker-metal3: {ansible_host: 192.168.1.56, mac: '6c:4b:90:47:8f:13', disk: sda, network_interface: eth0}
        worker-metal4: {ansible_host: 192.168.1.126, mac: '6c:4b:90:63:d4:b9', disk: sda, network_interface: eth0}
        worker-metal5: {ansible_host: 192.168.1.175, mac: '6c:4b:90:47:8e:fa', disk: sda, network_interface: eth0}
        worker-metal6: {ansible_host: 192.168.1.127, mac: '6c:4b:90:47:96:35', disk: sda, network_interface: eth0}





